/* Region lookup tables by console */
export const regions = {
  nds: {
    A: "asia",
    C: "china",
    P: "europe",
    E: "americas",
    J: "japan",
    F: "french",
    H: "dutch",
    I: "italian",
    K: "korean",
    L: "usa#2",
    M: "swedish",
    N: "norwegian",
    O: "international",
    Q: "danish",
    R: "russian",
    S: "spanish",
    T: "usa+aus",
    U: "australia",
    V: "eur+aus",
    W: "europe#3",
    X: "europe#4",
    Y: "europe#5",
    Z: "europe#5",
  } as Record<string, string>,
  gba: {
    J: "japan",
    E: "english",
    P: "europe",
    D: "german",
    F: "french",
    I: "italian",
    S: "spanish",
  } as Record<string, string>,
  gb: {
    0: "japan",
    1: "overseas",
  } as Record<number, string>,
  snes: {
    0: "japan",
    1: "americas",
    2: "europe",
    3: "sweden",
    4: "finland",
    5: "denmark",
    6: "france",
    7: "netherlands",
    8: "spain",
    9: "germany",
    10: "italy",
    11: "china",
    12: "indonesia",
    13: "south korea",
    14: "common / all",
    15: "canada",
    16: "brazil",
    17: "australia",
    18: "other variants",
  } as Record<number, string>,
  n64: {
    // Country code character at end of game code (ASCII)
    A: "Asia",
    B: "Brazil",
    C: "China",
    D: "Germany",
    E: "USA",
    F: "France",
    G: "Gateway 64 (NTSC)",
    H: "Netherlands",
    I: "Italy",
    J: "Japan",
    K: "Korea",
    L: "Gateway 64 (PAL)",
    N: "Canada",
    P: "Europe",
    S: "Spain",
    U: "Australia",
    W: "Scandinavia",
    X: "Europe",
    Y: "Europe",
    Z: "Europe",
  } as Record<string, string>,
} as const;

export type SupportedSystemsForRegions = keyof typeof regions;
