/* Hardware / mapper lookup tables */
export const specs = {
  nds: {
    unitcode: {
      "0": "nds",
      "1": "nds/dsi",
      "2": "dsi",
    },
  },
  sfc: {
    hardware: {
      "00": { coprocessor: false as const, rom: true },
      "01": { coprocessor: false as const, rom: true, ram: true },
      "02": { coprocessor: false as const, rom: true, ram: true, battery: true },
      "03": { coprocessor: "dsp", rom: true },
      "04": { coprocessor: "dsp", rom: true, ram: true },
      "05": { coprocessor: "dsp", rom: true, ram: true, battery: true },
      "06": { coprocessor: "dsp", rom: true, battery: true },
      "13": { coprocessor: "gsu/superFX", rom: true },
      "14": { coprocessor: "gsu/superFX", rom: true, ram: true },
      "15": { coprocessor: "gsu/superFX", rom: true, ram: true, battery: true },
      "16": { coprocessor: "gsu/superFX", rom: true, battery: true },
      "23": { coprocessor: "obc1", rom: true },
      "24": { coprocessor: "obc1", rom: true, ram: true },
      "25": { coprocessor: "obc1", rom: true, ram: true, battery: true },
      "26": { coprocessor: "obc1", rom: true, battery: true },
      "33": { coprocessor: "sa-1", rom: true },
      "34": { coprocessor: "sa-1", rom: true, ram: true },
      "35": { coprocessor: "sa-1", rom: true, ram: true, battery: true },
      "36": { coprocessor: "sa-1", rom: true, battery: true },
      "43": { coprocessor: "s-dd1", rom: true },
      "44": { coprocessor: "s-dd1", rom: true, ram: true },
      "45": { coprocessor: "s-dd1", rom: true, ram: true, battery: true },
      "46": { coprocessor: "s-dd1", rom: true, battery: true },
      "53": { coprocessor: "s-rtc", rom: true },
      "54": { coprocessor: "s-rtc", rom: true, ram: true },
      "55": { coprocessor: "s-rtc", rom: true, ram: true, battery: true },
      "56": { coprocessor: "s-rtc", rom: true, battery: true },
      e3: { coprocessor: "other", rom: true },
      e4: { coprocessor: "other", rom: true, ram: true },
      e5: { coprocessor: "other", rom: true, ram: true, battery: true },
      e6: { coprocessor: "other", rom: true, battery: true },
      f3: { coprocessor: "custom", rom: true },
      f4: { coprocessor: "custom", rom: true, ram: true },
      f5: { coprocessor: "custom", rom: true, ram: true, battery: true },
      f6: { coprocessor: "custom", rom: true, battery: true },
    },
    romspeed: {
      "20": { type: "LoROM", speed: "2.68MHz" },
      "21": { type: "HiROM", speed: "2.68MHz" },
      "23": { type: "SA-1" },
      "25": { type: "ExHiROM", speed: "2.68MHz" },
      "30": { type: "LoROM", speed: "3.58MHz" },
      "31": { type: "HiROM", speed: "3.58MHz" },
      "32": { type: "ExHiROM", speed: "3.58MHz" },
      "35": { type: "ExHiROM", speed: "3.58MHz" },
    },
  },
  nes: {
    mappers: {
      "0": "NROM",
      "1": "MMC1",
      "2": "UxROM",
      "3": "CNROM",
      "4": "MMC3",
      "5": "MMC5",
      "7": "AxROM",
      "9": "MMC2",
      "10": "MMC4",
      "11": "Color Dreams",
      "13": "CPROM",
      "15": "100-in-1 Contra Function 16",
      "16": "Bandai FCG-1/2 / LZ93D50",
      "18": "Jaleco SS88006",
      "19": "Namco 163",
      "21": "VRC4a/4c",
      "22": "VRC2a",
      "23": "VRC2b/4e",
      "24": "VRC6a",
      "25": "VRC2c/4b/4d",
      "26": "VRC6b",
      "34": "BNROM / NINA-001",
      "66": "GxROM",
      "69": "FME-7 / Sunsoft 5B",
      "71": "Camerica / Codemasters",
      "73": "VRC3",
      "75": "VRC1",
      "78": "Holy Diver / Irem",
      "79": "NINA-03/06",
      "85": "VRC7",
      "118": "TxSROM / MMC3",
      "119": "TQROM / MMC3",
      "210": "Namco 175/340",
    } as Record<string, string>,
  },
  gb_mbc: {
    "00": "ROM ONLY",
    "01": "MBC1",
    "02": "MBC1+RAM",
    "03": "MBC1+RAM+BATTERY",
    "05": "MBC2",
    "06": "MBC2+BATTERY",
    "08": "ROM+RAM",
    "09": "ROM+RAM+BATTERY",
    "0b": "MMM01",
    "0c": "MMM01+RAM",
    "0d": "MMM01+RAM+BATTERY",
    "0f": "MBC3+TIMER+BATTERY",
    "10": "MBC3+TIMER+RAM+BATTERY",
    "11": "MBC3",
    "12": "MBC3+RAM",
    "13": "MBC3+RAM+BATTERY",
    "19": "MBC5",
    "1a": "MBC5+RAM",
    "1b": "MBC5+RAM+BATTERY",
    "1c": "MBC5+RUMBLE",
    "1d": "MBC5+RUMBLE+RAM",
    "1e": "MBC5+RUMBLE+RAM+BATTERY",
    "20": "MBC6",
    "22": "MBC7+SENSOR+RUMBLE+RAM+BATTERY",
    fc: "POCKET CAMERA",
    fd: "BANDAI TAMA5",
    fe: "HuC3",
    ff: "HuC1+RAM+BATTERY",
  } as Record<string, string>,
  gb_rom_size: {
    "00": 32 * 1024,
    "01": 64 * 1024,
    "02": 128 * 1024,
    "03": 256 * 1024,
    "04": 512 * 1024,
    "05": 1024 * 1024,
    "06": 2 * 1024 * 1024,
    "07": 4 * 1024 * 1024,
    "08": 8 * 1024 * 1024,
    "52": 1152 * 1024,
    "53": 1280 * 1024,
    "54": 1536 * 1024,
  } as Record<string, number>,
  gb_ram_size: {
    "00": 0,
    "01": 2 * 1024,
    "02": 8 * 1024,
    "03": 32 * 1024,
    "04": 128 * 1024,
    "05": 64 * 1024,
  } as Record<string, number>,
} as const;

export type SupportedSystemsForSpecs = keyof typeof specs;
